[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PlantMeteo = "4630fe09-e0fb-4da5-a846-781cb73437b6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[sources]
PlantMeteo = { path = ".." }